name: build
on:
  push:
    branches: 
      - master
      - release/*
jobs:
  build:
    name: node-job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@2
      - name: use node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build --if-present        
